blank_issues_enabled: false
contact_links:
  - name: docs.microsoft.com site feedback
    url: https://github.com/MicrosoftDocs/feedback/issues/new/choose
    about: Log general docs.microsoft.com site issues here
  - name: Xamarin product feedback
    url: https://developercommunity.visualstudio.com/spaces/8/index.html
    about: Log product issues here
